---
- hosts: localhost
  gather_facts: no
  vars:
    state: absent
  tasks:
  - name: create a function
    lambda:
      state: "{{ state | default('present') }}"
      type: code
      function_name: ansible-tester
      runtime: python2.7
      code:
        S3Bucket: ivcs-package
        S3Key: lambda/lambda.zip
      timeout: 3
      handler: lambda.handler
      role: arn:aws:iam::123456789012:role/someAPI2LambdaExecRole
      description: just another lambda
      publish: True
  - name: display stuff
    debug: var=code
  - name: create alias for latest version
    lambda:
      state: "{{ state | default('present') }}"
      type: alias
      function_name: ansible-tester
      name: Dev
      version: '$LATEST'
      description: Latest development version.
  - name: show alias stuf...
    debug: var=response
  - name: create alias for version 12
    lambda:
      state: "{{ state | default('present') }}"
      type: alias
      function_name: ansible-tester
      name: V12
      version: '12'
      description: Version 12.
  - name: show alias stuf...
    debug: var=response
  - name: add permission to policy
    lambda:
      state: present
      type: policy
      function_name: ansible-tester
      statement_id: newperm146
      qualifier: '17'
      action: 'lambda:*'
      principal: '*'
      source_arn:
      source_account:
  - name: show policy stuff...
    debug: var=response



