---
- hosts: localhost
  gather_facts: no
  vars:
    state: present
  tasks:
  - name: Lambda policy for S3 event notifications
    lambda_policy:
      state: "{{ state | default('present') }}"
      function_name: functionName
      alias: Dev
      statement_id: lambda-s3-myBucket-create-data-log
      action: lambda:InvokeFunction
      principal: s3.amazonaws.com
      source_arn: arn:aws:s3:eu-central-1:123456789012:bucketName
      source_account: 123456789012
#      event_source_token:

