---
- hosts: localhost
  gather_facts: no
  vars:
    state: present
    project_folder: /path/to/deployment/package
    deployment_package: lambda.zip
    account: 123456789012
    version_to_delete: 0

  tasks:
  - name: AWS Lambda Function with all parameters
    lambda:
      state: "{{ state | default('present') }}"
      name: myLambdaFuntion
      publish: True
      description: lambda funtion description
      code_s3_bucket: package-bucket
      code_s3_key: "lambda/{{ deployment_package }}"
      local_path: "{{ project_folder }}/{{ deployment_package }}"
      runtime: python2.7
      timeout: 5
      handler: lambda.handler
      memory_size: 128
      role: "arn:aws:iam::{{ account }}:role/API2LambdaExecRole"
      version: "{{ version_to_delete }}"
      vpc_subnet_ids:
        - subnet-9993085c
        - subnet-99910cc3
      vpc_security_group_ids:
        - sg-999b9ca8
  - name: show results
    debug: var=lambda_facts

  - name: Minimal required parameters for Lambda Function
    lambda:
      state: "{{ state | default('present') }}"
      name: myLambdaFuntion
      code_s3_bucket: package-bucket
      code_s3_key: "lambda/{{ deployment_package }}"
      local_path: "{{ project_folder }}/{{ deployment_package }}"
      runtime: python2.7
      handler: lambda.handler
      role: "arn:aws:iam::{{ account }}:role/API2LambdaExecRole"
  - name: show results
    debug: var=lambda_facts
