---
- hosts: localhost
  gather_facts: no
  vars:
    state: present
  tasks:
  - name: create a function
    lambda:
      state: "{{ state | default('present') }}"
      type: code
      function_name: ansible-tester
      runtime: python2.7
      code:
        s3_bucket: ivcs-package
        s3_key: lambda/lambda.zip
      timeout: 3
      handler: lambda.handler
      role: arn:aws:iam::469333712854:role/API2LambdaExecRole
      description: VPC endpoint lambda function
      vpc_config:
        subnet_ids:
        - subnet-77d3085c
        - subnet-b4910cc3
        security_group_ids:
        - sg-cc2b9ca8
      publish: False
  - name: display stuff
    debug: var=results
