---
- hosts: localhost
  gather_facts: no
  vars:
    state: present
    bucket: ivcs-package
  tasks:
  - name: add/deleted s3 event notifications to/from a lambda function
    s3_lambda_event:
      state: "{{ state | default('present') }}"
      bucket: "{{ bucket }}"
      lambda_function_configurations:
      - id: lambda-package-hello-prod
        lambda_function_arn: arn:aws:lambda:us-east-1:469333712854:function:hello:Prod
        events: [ 's3:ObjectCreated:*' ]
  - name: display stuff
    debug: var=results
