---
- hosts: localhost
  gather_facts: no
  vars:
    state: present
  tasks:
  - name: SNS event mapping
    lambda_event:
      state: "{{ state | default('present') }}"
      event_source: sns
      function_name: ingestData
      alias: Dev
      source_params:
        id: lambda-sns-topic-notify
        topic_arn: arn:aws:sns:us-east-1:469333712854:sns-lambda
        # enabled: True

  - name: show source event cnfig
    debug: var=lambda_sns_events
