---
- hosts: localhost
  gather_facts: no
  vars:
    state: present
  tasks:
  - name: create a function
    lambda:
      state: "{{ state | default('updated') }}"
      type: version
      function_name: ansible-tester
      description: Latest version of this function
  - name: display stuff
    debug: var=results
